Update plugin to support ASU Directory and add new action hooks
gios-asu/gios-cas-maestro pull request #1
Opened 2016-09-19 15:26 UTC by nathan-rollins

Sorry, there is probably more in here than should be in a single PR. The main focus was to add support for ASURITE users. This involves adding support for pulling user info from the ASU Directory, and revamping the language throughout the plugin, particularly in the settings views, to make it clearer how to use the plugin.

New action hooks were also added and described in the README. Most other changes to the plugin are minor and were the result of reviewing the plugin logic and debugging the behavior in the user registration process.

2016-09-19 16:44 UTC, nathan-rollins commented
I just remembered I wanted to run this plugin through phpcs and phpcbf to clean up coding standards.

2016-09-19 20:08 UTC, rraub commented on vendors/asurite/asu_directory.php
> +class ASUDirectory {
This being copy/pasted in isn't my favorite way to do this.. but adding composer just for this file is a bit of work too.  The only reason I bring this up is that these directory endpoints will be going away "soon" and we'll need to figure out equivalent ones using the new iSearch tools.

2016-09-19 20:08 UTC, rraub requested changes

2016-09-19 20:08 UTC, rraub commented on cas-maestro.php
>            'server_hostname' => 'yourschool.edu',
Since this is the "ASU" Version can we set this to 'weblogin.asu.edu' ?

2016-09-19 20:08 UTC, rraub commented on cas-maestro.php
>            'server_path' => '',
also can we add `cas` to the default server path?

2016-09-19 20:08 UTC, rraub commented on cas-maestro.php
> +        // add_action('password_reset', array(&$this, 'disable_function'));
Why did these actions get removed?

2016-09-19 20:08 UTC, rraub commented on cas-maestro.php
>     * Generates a random string with a lenght
typo: leng**T**h

2016-09-19 20:08 UTC, rraub commented on cas-maestro.php
> +    $this->_write_log( __CLASS__ . '.' . __FUNCTION__ . ' (' . __LINE__ . ') : ' );
are all these log messages just for debugging?

2016-09-19 20:28 UTC, rraub commented
also we should make some changes to the header of cas-maestro.php so that our plugin wont get updated and overridden if there is ever another update from the official source for CAS Maestro.

2016-09-20 16:26 UTC, nathan-rollins commented on cas-maestro.php
> +        // add_action('password_reset', array(&$this, 'disable_function'));
Oops. I jumped the gun on issuing this PR. Those are just temporarily disabled until I work out a minor routing issue with non-CAS users. I described it in the specific commit, but obviously should have also added a TODO/FIXME comment.

2016-09-20 16:30 UTC, nathan-rollins commented on cas-maestro.php
>     * Generates a random string with a lenght
I don't understand what you are pointing out.

2016-09-20 16:33 UTC, nathan-rollins commented on cas-maestro.php
> +    $this->_write_log( __CLASS__ . '.' . __FUNCTION__ . ' (' . __LINE__ . ') : ' );
Yeah, they only run when WP_DEBUG == TRUE. I was thinking I might remove them eventually.

2016-09-20 18:33 UTC, rraub commented on cas-maestro.php
>     * Generates a random string with a lenght
the comment says "lenght" not "length", its not worth digging in just to fix it, but if you already are working on that file then its a quick fix. Chances are its spelled wrong in the original plugin.

2016-09-20 21:41 UTC, nathan-rollins commented on cas-maestro.php
>     * Generates a random string with a lenght
Oh, hah. I was focused on the edited part of that preview.

2016-10-10 20:46 UTC, rraub approved these changes

2016-10-10 20:46 UTC, merged